#Turn off DNS functionality for dnsmasq:
port=0

#Subnet 10.1.1.0/24:
dhcp-range=set:pool-10110,10.1.1.100,10.1.1.200,255.255.255.0,8h
#Assign option 3 (Default gateway) to clients:
dhcp-option=tag:pool-10110,option:router,10.1.1.31

#Subnet 10.1.2.0/24:
dhcp-range=set:pool-10120,10.1.2.100,10.1.2.200,255.255.255.0,8h
#Assign option 3 (Default gateway) to clients:
dhcp-option=tag:pool-10120,option:router,10.1.2.32
